### PR TITLE
Invoke parent serializer method instead of object method with the same name

### LINKED ISSUE #115: Can't redefine object method with inheritance
If parent serializer redefines object's method it's not invoked in child serializer and calls object's method (same behaviour with modules)

```
require 'surrealist'

class User
  def first
    2
  end
end

class User::BaseSerializer < Surrealist::Serializer
  def first
    object.first * 2
  end
end

class UserSerializer < User::BaseSerializer
  json_schema { { first: Integer } }
end

user = User.new

p UserSerializer.new(user).build_schema
# prints {:first=>2} 
# should be {:first=>4} 

```
I believe this is because of `false` argument for `instance_methods` [here](https://github.com/nesaulov/surrealist/blob/master/lib/surrealist/value_assigner.rb#L50)
Bug or feature?

### PR DESCRIPTION
**Pull request by kolasss**
Fix #115

### CODE REVIEW

**Comment by kolasss** [comment]
looks like build is failing because of #117

**Comment by kolasss** [comment]
I have checked the dependencies, and i am sure the culprit is the gem 'dry-initializer', '2.6.0', locally with 2.5.0 specs are passing

**Comment by nesaulov** [comment]
Hey @kolasss thank you for the PR! I am looking into the specs problem right now, as I can see, tests are failing in master branch as well.

**Comment by nesaulov** [comment]
As I can see, you are right (see https://github.com/dry-rb/dry-initializer/commit/d44fb38c26853e9c004d679a0d7dc7be8751c113)
I have restarted the build, lets see where it takes us.

**Comment by nesaulov** [comment]
I have dropped the bundler cache and it seems it helped. I will review this PR today or tomorrow.

**Pull request merged**
